<a href="https://colab.research.google.com/github/Mayte-Otavalo/Python/blob/main/Preparation_of_the_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install liac-arff

Requirement already satisfied: liac-arff in /usr/local/lib/python3.12/dist-packages (2.5.0)

In [ ]:
import arff
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Funciones auxiliares

In [ ]:
def load_kdd_dataset(data_path):
    """Reading the NSL-KDD dataset."""
    with open(data_path, 'r') as train_set:
        dataset = arff.load(train_set)
    attributes = [attr[0] for attr in dataset["attributes"]]
    return pd.DataFrame(dataset["data"], columns=attributes)

In [ ]:
def train_val_test_split(df, rstate=42, shuffle=True, stratify=None):
    strat = df[stratify] if stratify else None
    train_set, test_set = train_test_split(
        df, test_size=0.4, random_state=rstate, shuffle=shuffle, stratify=strat)
    strat = test_set[stratify] if stratify else None
    val_set, test_set = train_test_split(
        test_set, test_size=0.5, random_state=rstate, shuffle=shuffle, stratify=strat)
    return (train_set, val_set, test_set)

# 1. Reading the dataset

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Yachay Tech/SEPTIMO/INGENIERÍA DE SOFTWARE/archive/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [ ]:
train_set, val_set, test_set = train_val_test_split(df, stratify='SeniorCitizen')

In [ ]:
print("Length of the Training Set:", len(train_set))
print("Length of the Validation Set:", len(val_set))
print("Length of Test Set:", len(test_set))

Length of the Training Set: 4225
Length of the Validation Set: 1409
Length of Test Set: 1409

# 3 Cleaning the data

Before we start, we are going to retrieve the clean dataset and separate the labels from the rest of the data, we do not necessarily want to apply the same transformations on both sets.

In [ ]:
# Display basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
# We separate the input characteristics from the output characteristic.
X_train = train_set.drop("Churn", axis=1)
y_train = train_set["Churn"].copy()

In [ ]:
# To illustrate this section let's add some null values
# to some characteristics of the dataset
X_train.loc[(X_train["MonthlyCharges"]>40) & (X_train["MonthlyCharges"]<17.250000), "MonthlyCharges"] = np.nan
X_train

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
4734,4106-HADHQ,Male,0,Yes,Yes,39,Yes,No,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,No,Credit card (automatic),NaN,3182.95
5544,9572-MTILT,Male,0,Yes,No,59,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,No,Month-to-month,Yes,Electronic check,NaN,6252.9
5994,9661-ACXBS,Female,0,No,No,42,Yes,Yes,Fiber optic,Yes,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,NaN,4400.75
6330,9921-QFQUL,Female,0,Yes,No,23,Yes,Yes,Fiber optic,No,No,Yes,No,No,Yes,Month-to-month,No,Mailed check,NaN,2044.95
2731,1110-KYLGQ,Female,0,No,No,63,Yes,Yes,Fiber optic,Yes,Yes,Yes,No,Yes,Yes,Month-to-month,No,Credit card (automatic),NaN,6780.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,6467-CHFZW,Male,0,Yes,Yes,47,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,NaN,4749.15
6223,2575-GFSOE,Female,0,Yes,Yes,7,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,506.9
5054,6094-ZIVKX,Female,0,No,No,68,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,Yes,Credit card (automatic),NaN,3674.95
4796,3807-BPOMJ,Female,0,Yes,No,55,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,One year,Yes,Electronic check,NaN,5276.1
264,1950-KSVVJ,Female,0,Yes,No,45,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,One year,No,Mailed check,NaN,5032.25

In [ ]:
# We check if there is any attribute with null values
X_train.isna().any()

customerID          False
gender              False
SeniorCitizen       False
Partner             False
Dependents          False
tenure              False
PhoneService        False
MultipleLines       False
InternetService     False
OnlineSecurity      False
OnlineBackup        False
DeviceProtection    False
TechSupport         False
StreamingTV         False
StreamingMovies     False
Contract            False
PaperlessBilling    False
PaymentMethod       False
MonthlyCharges       True
TotalCharges        False
dtype: bool

In [ ]:
# Display statistical information about the dataset
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [ ]:
# Select rows containing null values
null_rows_values  = X_train[X_train.isnull().any(axis=1)]
null_rows_values

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
4734,4106-HADHQ,Male,0,Yes,Yes,39,Yes,No,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,No,Credit card (automatic),NaN,3182.95
5544,9572-MTILT,Male,0,Yes,No,59,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,No,Month-to-month,Yes,Electronic check,NaN,6252.9
5994,9661-ACXBS,Female,0,No,No,42,Yes,Yes,Fiber optic,Yes,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,NaN,4400.75
6330,9921-QFQUL,Female,0,Yes,No,23,Yes,Yes,Fiber optic,No,No,Yes,No,No,Yes,Month-to-month,No,Mailed check,NaN,2044.95
2731,1110-KYLGQ,Female,0,No,No,63,Yes,Yes,Fiber optic,Yes,Yes,Yes,No,Yes,Yes,Month-to-month,No,Credit card (automatic),NaN,6780.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,6467-CHFZW,Male,0,Yes,Yes,47,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,NaN,4749.15
6223,2575-GFSOE,Female,0,Yes,Yes,7,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,506.9
5054,6094-ZIVKX,Female,0,No,No,68,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,Yes,Credit card (automatic),NaN,3674.95
4796,3807-BPOMJ,Female,0,Yes,No,55,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,One year,Yes,Electronic check,NaN,5276.1
264,1950-KSVVJ,Female,0,Yes,No,45,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,One year,No,Mailed check,NaN,5032.25

In [ ]:
# We copy the dataset so as not to alter the original.
X_train_copy = X_train.copy()

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

In [ ]:
# The imputer class does not support categorical values, we remove categorical attributes.
X_train_copy_num = X_train_copy.select_dtypes(exclude=['object'])
X_train_copy_num.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4225 entries, 4734 to 264
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SeniorCitizen   4225 non-null   int64
 1   tenure          4225 non-null   int64
 2   MonthlyCharges  1107 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 132.0 KB

In [ ]:
# Numerical attributes are provided to calculate the values.
imputer.fit(X_train_copy_num)

SimpleImputer(strategy='median')

In [ ]:
# We fill in the null values
X_train_copy_num_nonan = imputer.transform(X_train_copy_num)

In [ ]:
# Transform the result to a Pandas DataFrame
X_train_copy = pd.DataFrame(X_train_copy_num_nonan, columns=X_train_copy_num.columns)

In [ ]:
X_train_copy.head(10)

   SeniorCitizen  tenure  MonthlyCharges
0            0.0    39.0           20.35
1            0.0    59.0           20.35
2            0.0    42.0           20.35
3            0.0    23.0           20.35
4            0.0    63.0           20.35
5            0.0     2.0           20.35
6            0.0    47.0           20.15
7            0.0    52.0           20.35
8            0.0     3.0           20.35
9            1.0     4.0           20.35

## 4. Transformation from categorical to numerical attributes

In [ ]:
X_train = train_set.drop("gender", axis=1)
y_train = train_set["gender"].copy()

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4225 entries, 4734 to 264
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        4225 non-null   object
 1   SeniorCitizen     4225 non-null   int64
 2   Partner           4225 non-null   object
 3   Dependents        4225 non-null   object
 4   tenure            4225 non-null   int64
 5   PhoneService      4225 non-null   object
 6   MultipleLines     4225 non-null   object
 7   InternetService   4225 non-null   object
 8   OnlineSecurity    4225 non-null   object
 9   OnlineBackup      4225 non-null   object
 10  DeviceProtection  4225 non-null   object
 11  TechSupport       4225 non-null   object
 12  StreamingTV       4225 non-null   object
 13  StreamingMovies   4225 non-null   object
 14  Contract          4225 non-null   object
 15  PaperlessBilling  4225 non-null   object
 16  PaymentMethod     4225 non-null   object
 17  MonthlyCharges    4225 non-null   float64
 18  TotalCharges      4225 non-null   object
 19  Churn             4225 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 693.2+ KB

In [ ]:
Dependents = X_train['Dependents']
Dependents_encoded, categorias = Dependents.factorize()

In [ ]:
# We show on the screen how they have been coded
for i in range(10):
    print(Dependents.iloc[i], "=", Dependents_encoded[i])

Yes = 0
No = 1
No = 1
No = 1
No = 1
No = 1
No = 1
No = 1
No = 1
No = 1

In [ ]:
print(categorias)

Index(['Yes', 'No'], dtype='object')

# Advanced sklearn transformations

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

Dependents = X_train[['Dependents']]

ordinal_encoder = OrdinalEncoder()
Dependents_encoded = ordinal_encoder.fit_transform(Dependents)

In [ ]:
# We show on the screen how they have been coded
for i in range(10):
    print(Dependents["Dependents"].iloc[i], "=", Dependents_encoded[i])

Yes = [1.]
No = [0.]
No = [0.]
No = [0.]
No = [0.]
No = [0.]
No = [0.]
No = [0.]
No = [0.]
No = [0.]

In [ ]:
print(ordinal_encoder.categories_)

[array(['No', 'Yes'], dtype=object)]

# One-Hot Encoding

In [ ]:
Generates for each category of the categorical attribute a binary array representing the value.

In [ ]:
# The sparse matrix only stores the position of values that are not '0' to save memory.
from sklearn.preprocessing import OneHotEncoder

Dependents = X_train[['Dependents']]

oh_encoder = OneHotEncoder()
Dependents_oh = oh_encoder.fit_transform(Dependents)
Dependents_oh

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4225 stored elements and shape (4225, 2)>

In [ ]:
# Convert the sparse matrix to a Numpy array
Dependents_oh.toarray()

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [ ]:
# We show on the screen how they have been coded
for i in range(10):
    print(Dependents["Dependents"].iloc[i], "=", Dependents_oh.toarray()[i])

Yes = [0. 1.]
No = [1. 0.]
No = [1. 0.]
No = [1. 0.]
No = [1. 0.]
No = [1. 0.]
No = [1. 0.]
No = [1. 0.]
No = [1. 0.]
No = [1. 0.]

In [ ]:
print(ordinal_encoder.categories_)

[array(['No', 'Yes'], dtype=object)]

#### Get Dummies

In [ ]:
pd.get_dummies(X_train['Dependents'])

         No    Yes
4734  False   True
5544   True  False
5994   True  False
6330   True  False
2731   True  False
...     ...    ...
26    False   True
6223  False   True
5054   True  False
4796   True  False
264    True  False

[4225 rows x 2 columns]

## 5. Scaling the dataset

In [ ]:
X_train = train_set.drop("SeniorCitizen", axis=1)
y_train = train_set["SeniorCitizen"].copy()

In [ ]:
from sklearn.preprocessing import RobustScaler

scale_attrs = X_train[['SeniorCitizen', 'MonthlyCharges']]

robust_scaler = RobustScaler()
X_train_scaled = robust_scaler.fit_transform(scale_attrs)

X_train_scaled = pd.DataFrame(X_train_scaled, columns=['SeniorCitizen', 'MonthlyCharges'])

KeyError: "['SeniorCitizen'] not in index"